### ISSUE TITLE
Can't get add JCMathLib to work with two ECPoints

### ISSUE THREAD

**Issue by JFBB** [OpenCryptoProject/JCMathLib#25]
Hello, I downloaded the latest version of JCMathLib and got the below errors.
I then downloaded the latest release (JCMathLib 1.1.0) and got the same result.

I need to be able to add two public keys (BrainpoolP256R1) and read the result. Can you help, please?

            ECConfig ecc = new ECConfig((short)256);
            ECCurve curve = new ECCurve(false, SecP256r1.p, SecP256r1.a, SecP256r1.b, SecP256r1.G, SecP256r1.r);
            ECPoint point1 = new ECPoint(curve, ecc.ech);
            ECPoint point2 = new ECPoint(curve, ecc.ech);
            point1.randomize(); 
            point2.randomize(); 
            point1.add(point2);

This gave a Crypto error.

I also tried

            ECConfig ecc = new ECConfig((short)256);
            ECCurve curve = new ECCurve(
                    false,
                    Brainpool256R1.getFp(),
                    Brainpool256R1.getA(),
                    Brainpool256R1.getB(),
                    Brainpool256R1.getG(),
                    Brainpool256R1.getR()
                    );
            ECPoint point1 = new ECPoint(curve, ecc.ech);
            ECPoint point2 = new ECPoint(curve, ecc.ech);
            point1.setW(cryptoBuf, (short)0, hashLen);
            point2.setW(CA, (short)0, (short)CA.length);
            point1.add(point2);

This gave the same error.

**Comment by tintin10q** [comment]
I have the same issue I get 

```Exception in thread "main" javacard.framework.ISOException
        at javacard.framework.ISOException.throwIt(Unknown Source)
        at opencrypto.jcmathlib.Bignat.mod_exp(Bignat.java:1735)
        at opencrypto.jcmathlib.ECPoint.multiplication_x(ECPoint.java:415)
        at opencrypto.jcmathlib.ECPoint.multiplication(ECPoint.java:361)
        at opencrypto.jcmathlib.ECPoint.multiplication(ECPoint.java:345)
        at testTerminal.testTerminal.doMutualAuthentication(testTerminal.java:307)
        at testTerminal.testTerminal.main(testTerminal.java:376)
        at Main.main(Main.java:68)```

**Comment by dufkan** [comment]
Hi, on which card are you trying to use JCMathLib? Is it one of the cards on which JCMathLib has been tested? I would recommend using the new version of the library, currently in PR #28, which extended its support to more cards.
